services:
  broker1:
    image: kafka-arm64:kraftdev
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - type: bind
        source: ./config
        target: /config

    environment:
      NODE_ID: 1
      ADVERTISED_LISTENERS: leonardo:9092
      CONTROLLER_QUORUM_VOTERS: 1@leonardo:9093,2@leonardo:9095
      CLUSTER_ID: lYuvdNyUS-6NVz4-GMOT2g

  broker2:
    image: kafka-arm64:kraftdev
    ports:
      - 9094:9092
      - 9095:9093
    volumes:
      - type: bind
        source: ./config
        target: /config
    environment:
      NODE_ID: 2
      ADVERTISED_LISTENERS: leonardo:9094
      CONTROLLER_QUORUM_VOTERS: 1@leonardo:9093,2@leonardo:9095
      CLUSTER_ID: lYuvdNyUS-6NVz4-GMOT2g
